# -*- coding: utf-8 -*-
"""EDA_LK5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W3fdJYXWrUvfDKkgRdxpgMpsDTqIHag0
"""


import pandas as pd
from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/Users/iskandar/Development/BelajarPython/ProjectAkhir/data/raw/Penyebab Kematian di Indonesia yang Dilaporkan - Raw.csv")
# display(df.head())

# 1. Cleaning Data
# df.info()
# df.isnull().sum()

# Distribusi data numerik (Histogram)
# untuk melihat sebaran & skewness
num_cols = [
    "Year",
    "Data Redundancy",
    "Total Deaths",
]

print(df[num_cols].hist(figsize=(12,8),bins=15))

df["Total Deaths"] = df["Total Deaths"].fillna(df["Total Deaths"].mean())
print(df.isnull().sum())

# df["jumlah_penyakit"] = df["jumlah_penyakit"].fillna(df["jumlah_penyakit"].mode()[0])
# df["tingkat_pendidikan"] = df["tingkat_pendidikan"].fillna(df["tingkat_pendidikan"].mode()[0])
# df.isnull().sum()

# #Boxplot untuk Deteksi Outlier

# plt.figure(figsize=(12,8))
# sns.boxplot(data=df[num_cols])
# plt.title("Boxplot Data Numerik (Outlier Detection)")
# plt.xticks(rotation=45)
# plt.show()

# # Distribusi data kategorikal (Count Plot)

# cat_cols = [
#     "tingkat_pendidikan",
#     "jenis_pekerjaan",
#     "kepemilikan_bpjs",
#     "kategori_biaya_kesehatan",
# ]

# plt.figure(figsize=(14,8))
# for i, col in enumerate(cat_cols, 1):
#     plt.subplot(2,2,i)
#     sns.countplot(data=df, x=col)
#     plt.title(f"Distribusi - {col}")
#     plt.xticks(rotation=45)
# plt.tight_layout()
# plt.show()

# # Hubungan Feature Numerik vs Target Regresi (Scatter Plot)
# plt.figure(figsize=(12,8))
# plt.subplot(2,2,1)
# sns.scatterplot(data=df, x="pendapatan_bulanan", y="biaya_kesehatan")
# plt.title("Scatter Plot - Pendapatan Bulanan vs Biaya Kesehatan")
# '''
# Pola Hubungan
# Titik-titik menyebar cukup acak
# Tidak terlihat pola naik atau turun yang jelas

# 👉 Artinya:

# Tidak ada hubungan yang kuat antara pendapatan dan biaya kesehatan
# '''

# plt.subplot(2,2,2)
# sns.scatterplot(data=df, x="jumlah_penyakit", y="biaya_kesehatan")
# plt.title("Scatter Plot - Jumlah Penyakit vs Biaya Kesehatan")

# '''
# Jumlah penyakit memiliki pengaruh terhadap biaya kesehatan (hubungan positif)
# '''

# plt.subplot(2,2,3)
# sns.scatterplot(data=df, x="usia_kepala_keluarga", y="biaya_kesehatan")
# plt.title("Scatter Plot - Usia vs Biaya Kesehatan")

# #Tidak ada hubungan yang kuat antara usia dan biaya kesehatan

# plt.subplot(2,2,4)
# sns.scatterplot(data=df, x="jarak_faskes", y="biaya_kesehatan")
# plt.title("Scatter Plot - Jarak Faskes vs Biaya Kesehatan")

# plt.show()

# # 6 Perbandingan Kategorikal vs Target Numerik (Boxplot)
# plt.figure(figsize=(12,6))

# plt.subplot(1, 2, 1)
# sns.boxplot(data=df, x="kepemilikan_bpjs", y="biaya_kesehatan")
# plt.title("BPJS vs Biaya Kesehatan")

# plt.subplot(1, 2, 2)
# sns.boxplot(data=df, x="jenis_pekerjaan", y="biaya_kesehatan")
# plt.title("Jenis Pekerjaan vs Biaya Kesehatan")
# plt.xticks(rotation=30)

# plt.tight_layout()
# plt.show()

# # 7 Korelasi Antar Variabel Numerik (Heatmap)
# plt.figure(figsize=(10,8))

# sns.heatmap(
#     df[num_cols].corr(),
#     annot=True,
#     cmap="coolwarm",
#     fmt=".2f"
# )
# plt.xticks(rotation=30)
# plt.title("Heatmap Korelasi Variabel Numerik")
# plt.show()

# sns.pairplot(
#   df,
#   vars=["pendapatan_bulanan", "jumlah_penyakit", "usia_kepala_keluarga", "biaya_kesehatan"],
#   hue="kategori_biaya_kesehatan"
# )
# plt.show()